### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by akiyamaSM**

### CODE REVIEW

**Comment by AbderrahimSoubaiElidrissi** [comment]
Hi @akiyamaSM the `ooopla7` is the command so `ooopla7` on readme.md is correct

**Comment by akiyamaSM** [comment]
I guess there is an 'o' missing in the readme file

**Comment by AbderrahimSoubaiElidrissi** [comment]
Yes, correct I will merge it :nerd_face:

**Comment by akiyamaSM** [comment]
🙏🙏🙏 thaanks

**Pull request merged**
